### ISSUE TITLE
halp

### ISSUE THREAD

**Issue by PHZ710** [aleksilassila/Islands#17]
im gonna be completly honest I have almost no idea what im doing or how to do it. is it possible for you or someone to upload a video showing how to install and set it up correctly? Im getting confused on all these commands i need to put in and where and what plugins are required. 
A couple other questions: Does this work on papermc (idk if theres any real diff in all the versions or whatever)? is multiverse required if Im runnning a small private server and I just wanna be able to jump off the islands and into the wilderness and not have a bunch of other fancy worlds going? idk if it matters but im running the server through Shockbyte. at this point im almost willing to just pay someone else to set it up for me since i just reset my server to try and install this

**Comment by aleksilassila** [comment]
Fear not, help is on the way! Right now I'm unable to do a video tutorial but I'll try to explain everything as clearly as possible here.

Firstly, you can use PaperMC and it's in fact recommended out of all options out there. I'll assume that you are starting with completely fresh server. So here's a step by step instructions:

1.  Start the server once and then shut it down so it creates all the server files for you. Accept EULA if you have to.
2. Download [Islands](https://www.spigotmc.org/resources/islands-home-islands-system.84303/), [GriefPrevention](https://www.spigotmc.org/resources/griefprevention.1884/) and [VoidGenerator](https://www.spigotmc.org/resources/voidgenerator.25391/) plugin jars and place the jars inside a folder called `plugins` in your server.
3. In your server files there should be config file called `bukkit.yml`. Open that file and **add** the following lines at the bottom:
```
worlds:
  world:
    generator: VoidGenerator:PLAINS
```
4. Inside your server files there should be a **folder** called `world`. Delete that world and start your server again. 

Congratulations, you have successfully configured the plugin =)

Now, since you only play with your friends, I'd recommend you to give all permissions to all players, so in *server console* do `/op <name>` to make a player admin. Repeat for all the players.

After that, all players should have access to all commands. Your players can create new islands using `/is create`, which will open a simple GUI. `/home` command will get you back to your island after you jump down.

That should be pretty much it. There's a lot more configuration you can do if you have to, but you can worry about it later (if you want to). It's all documented in [Wiki](https://github.com/aleksilassila/Islands/wiki) if you are interested. Let me know if you have any further questions / problems with the setup.

Cheers!

**Comment by PHZ710** [comment]
I think I did it wrong somehow but I followed all your steps but when I created an island and do /home it doesnt take me to any islands just the main non island world. 
I just did some more testong before commenting and found an island was genning on the ground. 
Ok i just got home and realized I never submitted this so Im going at another attempt and following your instructions again. Will update you if i have any issues or notes or anything

**Comment by PHZ710** [comment]
wait is a certain way that i set up my settings so that theres an island world and then you drop into a wilderness/resource world that is separate? im poking around my plugins config files or whatever theyre called

**Comment by PHZ710** [comment]
Ok so i did something right and something wrong or all wrong cuz this time when I joined I was on a single peice of bedrock in the sky but when I went to try and create any island the sizes wouldnt show up at all when it told me to choose so there was nothing to click. I jumped tho to see what would happened and I fell for a while before it put me into a separate resource world so at least I guess thats right?

**Comment by aleksilassila** [comment]
Based on your earlier comments you didn't set up VoidGenerator correctly. Anyways, seems like now it's alright done you spawned on a bedrock which is good. If you didn't see any sizes when creating an island, go to server console and give yourself op permissions with /op name.
