### ISSUE TITLE
don't get island size's

### ISSUE THREAD

**Issue by DarkWolfNL611** [aleksilassila/Islands#18]
hey i just installed the plugin onto the server, so far everything works except when i create a island and come to choosing a size. evrything is empty. and maybe if you want i would love to hear everything from you what you can do with it :)

**Comment by DarkWolfNL611** [comment]
fixed it but still love some help to set it up right

**Comment by aleksilassila** [comment]
What do you need help with? Oh and everything should be documented in [Wiki](https://github.com/aleksilassila/Islands/wiki)

**Comment by DarkWolfNL611** [comment]
at the moment how to creat bigger islands and how to add them

**Comment by DarkWolfNL611** [comment]
and seems that normal players cant create a island out of there own

**Comment by aleksilassila** [comment]
Check out the wiki on how to further configure the project. When it comes to normal players, they need to have correct permissions, which you can find in the permissions page in wiki. Or if the server is just for you and your friends, you can make them all admins with /op

**Comment by DarkWolfNL611** [comment]
and where do i change the permissions?

**Comment by aleksilassila** [comment]
These questions aren't really specific for this plugin, you can read about permissions online or find a YouTube video that will explain them, but essentially you're gonna need a **permissions plugin**. But as I said, alternatively you can just make everyone admin with /op.

**Comment by aleksilassila** [comment]
These questions aren't really specific for this plugin, you can read about permissions online or find a YouTube video that will explain them, but essentially you're gonna need a **permissions plugin**, LuckPerms fir example. But as I said, alternatively you can just make everyone admin with /op. 

I'm going to close this issue since it doesn't really concern the plugin, but you can su still comment here if you need specific help or something doesn't work.
