### ISSUE TITLE
players not landing on islands

### ISSUE THREAD

**Issue by GreyHammond** [aleksilassila/Islands#22]
after creating their island, when they use /home they are teleported beyond their island's land, and fall back into the void,

**Comment by aleksilassila** [comment]
This behavior can be caused by two things: Either you deleted your world without deleting plugins/Islands/islands.yml so the plugin thinks there is an island there, or then you changed the island grid size without resetting your world. In the first case, either delete your world and islands.yml, or go to the island that doesn't exist and then do /is recreate there.

Cheers

**Comment by GreyHammond** [comment]
This absolutely fixed my problem. Thank you for the quick response.
