### ISSUE TITLE
Limited chunk generation options

### ISSUE THREAD

**Issue by garrettdotyeah** [aleksilassila/Islands#3]
Hello,

I seem to be having an issue where there are only 7 biomes that you can choose to create an island from. I've correctly set up the generator settings, as well as made sure the config.yml/bukkit.yml settings are correct. I have tried deleting and regenerating the islandsSource world, yet I still can't pick other normal biomes.

Aside from the limited chunk generator options, the plugin is flawless and does not indicate anything else is wrong with it internally.

In addition to regenerating the world, I have also removed the biomeCache.yml and tried that with a fresh world generation on start - yet I'm still running into the same problem

Please view the attached screenshots below for an idea as to what I'm seeing on my end.
<img width="308" alt="Screen Shot 2020-10-11 at 1 15 54 AM" src="https://user-images.githubusercontent.com/58644129/95673664-810f6300-0b5f-11eb-804c-59943412dc58.png">

Best,
Garrett

**Comment by aleksilassila** [comment]
Hey,

I should probably add the explanation on how the island source biomes are generated to the readme. Anyways, I'll try to explain it briefly here. 

So the plugin creates islandSource world and then finds all biomes that are big enough in given area so that they could be used to create an island. This means that more common biomes in minecraft world will appear more and less common not so much. You can configure the size of the search area and search speed in config.yml. 

However, if you still keep getting **exactly** the same biomes every time after deleting sourceWorld and cache, the plugin may use the same seed for the world every time, which is of course not intended. If that's the case, I'll patch it asap. In the meantime, try to make the biome search are bigger via the config.yml.

Thanks for the feedback ^^

**Comment by aleksilassila** [comment]
It seems like there's no issue with source world seeds. I adjusted the default config values so that the biome search size is 3500 by default. You can also find further information about how the generation works [here](https://github.com/aleksilassila/Islands#how-does-it-work).
